### ISSUE TITLE
谈谈招聘与团队需要什么

### ISSUE THREAD

**Issue by csvwolf** [Zheaoli/weekly-share#2]
在年前面试面试到吐了，感觉到了很多人的焦虑和思维上的误区，也发现了一些市场上普遍存在的问题，内卷化的原因，除了从业人员接触代码的时间越来越早以外，还有一点就是从业者的焦虑导致的，因此今天突然想聊(cou)聊(geng)这(xin)个(la)。

### 源代码是否是标配
众所周知的是，市面上的 JD 永远会写的非常的牛逼，类似于：「精通 Vue.js」、「有 X 年工作经验」、「有性能优化经验」；如果是后端的话，可能就会写「数据库调优」「高并发」等等。这里就产生了一些解读上的问题：

1. 我只有 2 年经验，但是要求上写三年，我能不能投
2. 怎么样才能算精通，是不是精通了才能投
3. 我因为过去的工作场景原因缺乏一些经验，那我还能不能投

大多数人太过于在意 Job Description，甚至对于加分项也过于执著，导致了对大厂的一些神话和误解，导致了两个结果：「不敢投」和「进大厂人均精通」。

于是，卷卷心行为开始无限再演：培训班和网络课程开始从入门教程变成了教你学源代码；简历上人均看过源代码；由于人均看过源代码，源代码似乎成为了入行潜规则。

当然，先不提这一行为促生的次生市场，这一行为带来的负面影响实际上相当的大：这意味着我们没法通过这个要点来鉴别能力和个人兴趣了，而必须通过投入实际的面试成本来发现问题。而开发者也会觉得读了源代码（或者只是其二次解读）就算是「精通」这个框架了。——从能力评估上，这一内卷行为实际带来了相当大的灾害。

比如一个典型的 case，当我看到简历里写着「读过源代码，熟悉实现原理」之类的话的时候，我往往会问以下几个问题：

- 为什么是这么设计的
- 你从读源代码中学到了什么，你觉得是否有一些设计的不够好的地方，如果是你的话会考虑怎么去设计
- 有没有发现一些不好的地方甚至是 Bug，然后给他提一些 issue 或者 MR

而大部分「读过源代码」的人并不能回答出这些问题，因为本质上他们读的理由只是因为「市场要求」，而不是出于自己的想法，带着问题去看的。

### 是否需要相关的经验

但是，公司真的需要的是「读过源代码」的人吗——不是，实际上也不需要轮子大师，市面上大多数的岗位只是去满足一些业务或者基础设施上的需求，说实话就代码难度来说大部分工作都是没什么难度的，我们可以像分析产品的需求那样去分析一下公司的真实诉求：

1. 聪明的，学得快的
2. 有技术热情的，有自己的技术态度和想法的
3. 技术栈匹配或有类似技术栈可以快速上手的
4. 如果是一些关键岗位或者负责人，又或者需要快速匹配，那可能需要一些相关经验

前面三点很好理解，到了第四点，肯定又有不少人有烦恼了，大厂似乎一般都喜欢有大厂经验的，我之前在小厂，本身似乎就不带什么高并发的经验，我们也没有这个场景，这可怎么办好——这里仿佛是一个死循环，以高并发为例：「因为在小厂没有高并发经验」、「大厂需要有高并发经验的人」、「我进不了大厂」、「所以我还是没有高并发经验」。

仿佛变成了一种「大厂出身」的阶级固化，但是互联网作为一个新兴行业，本身不应该有「阶级固化」这种事情发生，于是和几位候选人聊了聊之后发现，他们并不是缺乏经验，又或者说经验本身并不是多么了不起的事情，只要有一个场景，有人带，很有可能马上就能会，但是为什么我们最后没有要他们，并不是因为他们缺乏经验，而是缺乏了「启发性思维」和「探索能力」，他们往往寄希望于公司能够教会他们什么，而不考虑在没有这些场景的时候自己也同样可以去做假设和思考。

破圈也很简单，只要从中加上一环，「在自己目前所有的规模和场景下，更进一步的去思考下一个规模或许能做的事情」。至少能保证你是满足了 1，2，3 点的人。

当然，对于很多人来说，可能就会变成一个「我是小公司负责人」却到「大公司搬砖」的抉择了，也引发了我们的下一个问题。

### 我 30K 的工资，怎么就得降薪了呢
工资等于技术，高工资等于一切也是消费主义的现在的一大陷阱，而且得益于各大网站和公众号的不断努力，把这个坑越挖越大，最终企业开始水涨船高的「人才引进」，而每个人都把高薪资当成衡量技术水平的其中一个要点。

当然，在我看来，大多数人创造的价值根本不值这个价钱，都是市场催生的泡沫，虽然我们都是在泡沫上跳舞的人，但是最好对泡沫本身有着清晰的认知。当然，也没有为某些给钱不给力的公司洗地的意思，从横向对比来看，不给力就是不给力，就算说「你本身不值这个价」，但是那也是在泡沫破碎之后的事情了，但是就现在而言，你的开价是多少，是否会降薪，取决于「你的工作时长」「你所站的位置泡沫有多大」「你的真实水平」三个要素，而个人水平只是其中一点，在现在来看，远远不是主要的决定因素（少部分人来看）。

## 团队需要什么
说了这么多，拒绝的候选人也不少，确实有迷之自信的，也有非常缺乏自信的人，上面也谈到了一些关于公司在招聘上的诉求，那么对于一个团队来说，团队除了一个人的技术水平（硬实力）以外，究竟还需要什么呢，「为什么我觉得我都回答出来了，但是却挂了」这种问题也屡见不鲜，达到了「这个我没法给你解释」的境界。

### 为什么我都答出来了却挂了
一般如果是通过微信找我内推的一些人，可能会在面试后问我一个这样的问题，他们觉得自己都答出来了，但是为什么面试官不要，这里就涉及到了以下几点可能的雷区：

1. 你背的实在太溜了，以至于看不到个人的真实思考——这一点面试官也有责任，毕竟没有完美的引导到你没背过的部分，但是半小时或者一小时的面试毕竟短暂，必须要双方配合才能挖掘水平。
2. 虽然……表面好像答出来了，实际上没答到点上或者跑偏了，这一点很像考试时候的作文跑题，表面上你洋洋洒洒写了 800 字，老师只给了你一个及格分；而其中最大的忌讳是，你跑偏是故意的，也就是「诱导面试官」，这属于唬住了 30K 唬不住 3K 的行为。
3. 你虽然答了，但和你简历本身不够匹配，或者说答案没有展现出简历里应有的水平，这一点会让人怀疑「简历注水」甚至是「造假」，尤其的雷区是如果你本身并不是项目负责人或者开源项目贡献者的时候却在简历里这么写。

### 为什么我技术可以却挂了
这里涉及到一个东西，叫做「软实力」，实际上，大部分团队在招人的时候按照比例，很大的 HC 都是给开发主力的，这种时候对于你的硬实力要求并不会非常高，但是却非常需要你的软实力，比如：

1. 沟通能力：这里指的是跟组内成员沟通，跟外部需求方的沟通等等，我个人认为无论是做业务的，还是基础设施的提供方，本质我们都是第三产业的生产者，也就是服务性行业，沟通永远是最需要掌握的能力。在实际面试过程中，我也会出一些看似铁憨憨的表述类题目，表面上仿佛是在考技术，其实是在考沟通和表达能力。
2. 情商：和沟通能力相对应的就是一个人的情商，和沟通能力一样，如果在面试过程中你让面试官感到不舒服且面试官没有失恋或者被老板骂，那大概率就会打上情商不行的标签。
3. 责任心：在聊项目的过程中非常容易能够看出一个人的责任心，现在的进口词汇叫做 Owner 意识，至少我本人来看是非常讨厌一个锅甩来甩去的，如果你想要去负责一个项目甚至是管理，那么这个意识是必不可少的。团队如果不想把成员当做消耗品，而是互相成就，也一定会考虑这个要素。
4. 潜力：很多人会觉得我技术跟你们其他几个人比要好上不少，为什么你们不要，你们是不是歧视大龄开发——实际上在面试时还有一个隐藏要点是，根据不同工作年限，我们对一个人会有一个大致的心理预期，同样的水平，我们更倾向于去选择年限小的，因为「潜力」更好，看上去也更有培养的价值。
5. 稳定性：很多团队会担心人员的稳定性，这也就是为什么往往不到一年就换工作的人我们都会问一句「为什么」，如果有正当的理由大可不必紧张，如果只是因为「钱」、「和预期不一致」的问题，那可能就会纠结好一会儿了——因为我没法保证我们是否满足你心里真实的想法。
6. 诚信：就算你夸得再好，一旦被发现你有吹牛，简历造假的嫌疑，那肯定是无脑 GG 的，即使只是简历注水，可能也会纠结好一会儿再去决定「是平台小导致的定位不准」还是「主观意愿上靠注水来投机」。

## 总结
当然，上文并不是说，看源代码就是在内卷，是错的，错的并不是「看源代码」这一行为，而是为了过面试急功近利的一些行为，本质上是「为了过面试而 XXX」，同理可得，「背面经」、「背基础题」也是一样的，有的人确实很会做题，记性也很好，甚至可能会唬过面试官，成功入职，但毕竟不是自己的真实水平；知识当然有可能被遗忘在海马体的某一个角落，但在面试聊天的过程中总会记起点什么，否则的话这就并非你的真实水平，在实际工作中也不可能灵活的被应用，那么这一些背诵篇目是没办法产生任何价值的。如果你之前读过或者听过我的演讲[「知识迁移——工程师多向发展的优势」](https://www.codesky.me/archives/knowledge-exchange.wind)就能知道，我的观点是，让不同分片的知识引起连锁，产生更大的价值，这才是我们想要的东西。

带着问题去思考，去看待一个事物，你才能收获更多属于自己的东西。（详情请见本系列第二章「如何研究一个问题」，如果不跳票的话）

这也就是为什么我一直鼓励大家放心大胆的投，JD 没什么好看的，因为 JD 的另一面，是和你一样焦虑的公司招聘方，他们建了一堵墙，隐藏了自己的本意，想要借此减少一点招聘成本罢了。

注：不排除少部分傻逼公司和面试官刁难人的可能性，但不是市场主流行为或者符合真实需求的行为。

当然，本文从某种角度上肯定牵涉了诸多利益方，因此或许会引起某一种灾难，所以最后声明：

以上，谨代表个人观点，不喜请点×，手机阅读请关闭本 Tab，拒绝口水键盘，从我做起。

**Comment by snowball-db** [comment]
现在面试官跟面试者感觉更像是一个互相卷的过程，面试官需要筛选出合适的同学，然后面试的过程通过经过数据清洗之后汇总成面经，几轮迭代之后面试流程的意义就逐渐降低了。我个人是很不喜欢卷lc以及八股文的，因为感觉没什么用，看源码因为基本上都是要做什么事情所以不得不看，就觉得还是有点意义的，但是这种思维其实很不适合面试对不对？

**Comment by lencx** [comment]
个人观点：
1. 解决问题的能力和掌握了xx技能并不是一个等价的关系，会xx技术，并不能代表就有了解决xx问题的能力。
2. 没有xx经验，我觉得很正常，人的精力都是有限的，不可能什么都去接触，但是学习和自我提升是必不可少的。就我了解而言，可能是人各有志，有些人在满足了日常开发任务之后，就很少去学习新知识了。技术层面我一直都认为学习的能力和解决问题的能力，才是一个人的核心竞争力。

**Comment by kioipp** [comment]
> 前面三点很好理解，到了第四点，肯定又有不少人有烦恼了，大厂似乎一般都喜欢有大厂经验的，我之前在小厂，本身似乎就不带什么高并发的经验，我们也没有这个场景，这可怎么办好——这里仿佛是一个死循环，以高并发为例：「因为在小厂没有高并发经验」、「大厂需要有高并发经验的人」、「我进不了大厂」、「所以我还是没有高并发经验」。

> 破圈也很简单，只要从中加上一环，「在自己目前所有的规模和场景下，更进一步的去思考下一个规模或许能做的事情」。至少能保证你是满足了 1，2，3 点的人。

心有戚戚焉，不断提升自我的诉求才是解决问题的根本动力，不然只会落入应试教育和面向面试编程的怪圈。
