### ISSUE TITLE
html标签img的在业务开发中的场景方案分享

### ISSUE THREAD

**Issue by gzqby** [Zheaoli/weekly-share#4]
#### 场景：

在账户找回业务场景中，需要使用用户的一部分信息，其中有图片信息。然后就出现一个问题，img标签src图片链接是不能显示的，然而用浏览器新开tab的方式是可以正常显示图片的。

#### 分析：

登陆态与非登陆态表现不同的原因在，登陆态的可以获取预先协议规则，使用非img标签形式获取资源，而非登陆不能。代码中与浏览器tab表现不同的原因在：有无**Referer**。

## 思考

> 线上image资源作为公开资源，不做一定的限制，面临问题的—盗链，以及带来的流量负担与版权问题

## 正反向方案

- 正向：怎么做资源保护与下载：
  1. 常规操作就是根据referer做判断，能做到浏览器可查看
  2. 如果浏览器不能查看只能下载需要response headers加：**Content-Disposition:attachment;filename=""**
  3. 当然img资源get也是http，所以可以协议param去过滤访问

- 反向：

  由于常规图片资源还是要兼容浏览器查看的，所以屏蔽referer就是应对方案。方法：

  1. 方法img标签referrerpolicy(兼容性有问题)
  2. `<meta name="referrer" content="no-referrer">`

**Comment by csvwolf** [comment]
有点没看懂，指的是通过 `img` 引入的内容没有 `refer` 吗，然后所以是怎么样解决的……

**Comment by gzqby** [comment]
<img src="someurl.png" />，这样不能正常显示-一个撕裂图标，这个url在浏览器中open into  tab是正常显示。就是这样的现象。解决方案就是屏蔽referer信息就可以了。当然符合预期的访问本身就是ok的。

**Comment by Zheaoli** [comment]
话说追加一个问题，对于 img 标签这种情况，有办法可以禁止右键 save image 么？但是不影响正常显示？

@zgoby
