### ISSUE TITLE
程序员生活-羽毛球

### ISSUE THREAD

**Issue by Zheaoli** [Zheaoli/weekly-share#8]
附言

本篇会介绍羽毛球的好处，基础以及个人心得（都是干货）。

笔者有个愿景：码代码中打球最好的，打球中码代码最好的（(￣▽￣)~*）。

备注：羽毛球运动前不要拉伸（打的比较激烈的情况下），不然更容易伤到自己，小时候广播体操式的热身就行，运动完以后一定要拉伸。（切记，切记）

好处

个人认为羽毛球是最适合程序员的运动之一，原因有以下

1.    上手门槛低但上限高，耐玩。

2.    单人、多人都可以玩，呼朋引伴不可少。

3.    涉及众多部位，包括：脚尖（新手也可以是整个脚掌）、腿部、头部、小臂、大臂、手指、背部（羽毛球唯一的缺点可能就是不易瘦肚子<(￣ ﹌ ￣)>）。

4.    不易受伤，通常老手比新手更容易受伤，但老手有自我保护意识（除了以羽毛球为生的师傅）

基础

球友有云：3分靠手，7分靠脚，剩下的90靠聪明的小脑瓜。

虽有夸张的成分，但通常在木有教练、自学的情况下，羽毛球学习路线大抵就是如此。（也就是野路子）

科普一下：羽毛球击球种类划分

按照出球效果分为：高远球，平高球，吊球，平抽以及扣球。

按照击球时站在球场的点位分为：前场球、中场球、后场球。

一）手

人人皆可羽毛球的原因就是，羽毛球击球容易：球大、拍子面广，球的减速能力堪称最强（毕竟是世界上最快的球类运动）。

通常而言，手指是唯一接触拍子的，所以请务必在击球的时候手指握紧拍子（小心暗器，食我飞拍啦）。而由这个引申出了手指的放松和握紧（毕竟一直握紧贼累），也就是所谓的瞬间发力。放松的时候，手掌和拍子应该能塞下一根食指的指尖至第二关节；值得注意的是，放松到握紧会造成拍子的小幅度偏移（正面击球可能会变为小幅度切球），这个也是大部分中高手们击球失误的原因（想攻克这个难点，只能自己寻找球感以及击球感，并将之变为肌肉记忆）。

击球分为：发力和击球点。发力就是球拍击打到球的时候，控制球拍对球施加的力（因为我们只能操控球拍，当然如果你会超能力另当别论）通常这个也叫力量把控，发力的核心是用更小的体力消耗打出更佳的效果；击球点就是球拍打到球的地方，影响球后续的飞行路线。

建个贝塞尔曲线模型如图1-1（为啥不是圆形，因为正常情况下，人不会是原地转大风车来打球），模拟下完整的击球：从左端点沿着该曲线至任意点，再沿该点的切线（出球），然后画出抛物线（飞行轨迹，这个就比较难模拟了，pass）至x,y。发力影响的就是画线速度。对了，我们所站的位置是x1,y的位置

![image](https://user-images.githubusercontent.com/7054676/109420779-2cd22600-7a0f-11eb-89b9-86fd891c7d35.png)

1-1

二）脚

脚的本质是通过自己的跑动来获取一个舒适的击球点以及发力准备。前者也就是平移x1,y来重新建模。而后者却是我们常常忽略的地方；实际上我们在跑动的时间里，只是动脚那就太浪费时间了（根据华罗庚先生的统筹法）脚在动的时候，手提前准备好击球方式是能极大提高击球效率（甚至有些大佬已经进化出了手带动人的本领，也就是所谓的脚未至，手先至）。

简单说一个可以迅速提高技术的方法（就是有些废脚）。跑的时候用脚尖，到了位置以后依旧前半脚掌撑地，脚跟半虚浮（请务必做好热身，不然使用该技巧，容易抽筋或者受伤）。

三）小脑瓜

为啥说羽毛球适合我们程序员呢，因为这个东东是要动脑瓜子的（不论是物理上，还是生理上），通过上述的说明也很能看出，羽毛球实际上结合了不少数学以及物理方面的知识。在此简单提几个套折磨人的击球套路：三长一短（也就是打三次后场球然后突然来个前场球），左右互搏（打一次左边再打一次右边），斜对角最长大法（羽毛球场地是长方形）。以上搭配使用风味更佳哦。

养成在打球的时候多想想，多思考会让我们走的更快，更高以及更远。

个人心得

打球不错，但容易上瘾。

羽毛球本质上是一种多人竞技类运动，所以判断一个人的水平以及能否从运动中获得乐趣，取决于他/她的对手。

下至只会 大风车 或者 乱披风挥拍的新手，上至万众瞩目、聚光灯聚焦于身的球馆大神，总有属于他们自己的搭子（伙伴）或者对手。所谓山外有山，人外有人，总有比你厉害的。所以打球可以输，但一定要打的帅。

**Comment by Zheaoli** [comment]
其实我有一个问题想请教。。打羽毛球会伤膝盖么？

**Comment by spencercjh** [comment]
> 其实我有一个问题想请教。。打羽毛球会伤膝盖么？

我觉得会的。膝盖是一个谁先用完谁先走的器官。况且不是专业队伍，缺乏科学保障。

羽毛球步法怎么练？ - Athlete的回答 - 知乎
https://www.zhihu.com/question/22608330/answer/322448915

不是靠这个吃饭的，平时打球多换换，多休息；多动脑多用技术而不是蛮力跑、跳。

**Comment by spencercjh** [comment]
> 其实我有一个问题想请教。。打羽毛球会伤膝盖么？

我觉得会的。膝盖是一个谁先用完谁先走的器官。

羽毛球步法怎么练？ - Athlete的回答 - 知乎
https://www.zhihu.com/question/22608330/answer/322448915

不是靠这个吃饭的，平时打球多换换，多休息；多动脑多用技术而不是蛮力跑、跳。

**Comment by SkyAndsola** [comment]
> 其实我有一个问题想请教。。打羽毛球会伤膝盖么？

膝盖受伤通常都是不规范的动作引起的。注意击球的时候，膝盖不要过分超过脚尖（不超过半个脚掌，以常规弓步为参考）。还有运动完要适当拉伸。
